### ISSUE TITLE
Lock read tokens: Check read pool exists before attempting a lock

### ISSUE THREAD

**Issue by stewartie4** [0chain/gosdk#104]
In order to lock read tokens (read_pool_lock) a read pool must first have been created for the wallet (new_read_pool).

When registering a wallet for the first time via the go sdk, it runs new_read_pool.
Calling the token lock function via the gosdk makes the assumption that new_read_pool has already been called successfully and only calls read_pool_lock.
**this is also an issue in explorer which calls the API directly, this will require a similar but separate fix**

This results in an inability to lock tokens when: 
1. A wallet was registered outside the sdk and new_read_pool was never called
2. new_read_pool was called but failed at the time due to network etc.

Proposed fix:
1. Get status of the client's read pool via getReadPoolAllocBlobberStat or similar. If a pool exists then continue with read_pool_lock, otherwise call new_read_pool then call read_pool_lock

Ref errors:
Explorer UI fails to lock tokens as new_read_pool has not been called
![image](https://user-images.githubusercontent.com/18306778/121753425-3f79f200-cb0a-11eb-898e-5131b71d7d99.png)

Response from sharder
![image](https://user-images.githubusercontent.com/18306778/121753461-528cc200-cb0a-11eb-9335-eff2c7971256.png)

**Comment by Sriep** [comment]
It would be easiest to change [readPoolLock](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/readpool.go#L336) in storagsc to automatically create a read pool if one is missing.

Is there any used case where we would want `read-pool-lock` to fail if there is not a read pool, rather than create one automatically?

**Comment by stewartie4** [comment]
Agreed, one should be created automatically I raised an issue to implement but see you've already raised https://github.com/0chain/0chain/pull/377 so I'll close
