### ISSUE TITLE
updateallocation with replace blobber returns `no enough size in allocation`

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#1050]
step to reproduce: 

1. create an allocation with size 2048

2. upload a file of size 1024, then the used size of the allocation an allocation changes to 2048

3. now when you replace a blobber with an other one, I get error: `no enough size in allocation`. 

when you replace the blobber, the used_size of the allocation changes to `1536`. So there is 512 bytes of storage available. Even though there is 512 bytes of data available in the allocation, we still get the above error. this is because we check against the actual file size 

meaning, issue only happens when we try to replace a blobber in an allocation when remaining size is 0

https://0chain.slack.com/archives/C02AV6MKT36/p1687115793572579?thread_ts=1686935002.932209&cid=C02AV6MKT36

**Comment by boddumanohar** [comment]
```
zbox newallocation --lock 1000 --data 2 --parity 2 --size 2048

# create a file
truncate -s 2048B file.txt

zbox upload --allocation $alloc --localpath ./file.txt --remotepath /file.txt
zbox updateallocation --allocation $alloc --add_blobber $blobber1 --remove_blobber $blobber2
```
steps to reproduce

**Comment by Kishan-Dhakan** [comment]
Resolved by https://github.com/0chain/0chain/pull/2563
