### ISSUE TITLE
`createAllocation` doesn’t respect the preferred blobbers sent over by the client

### ISSUE THREAD

**Issue by manasnisar** [0chain/gosdk#1054]
Ref: https://0chain.slack.com/archives/C03HUFQD01M/p1687195937985649

**Comment by boddumanohar** [comment]
the token to be locked in allocation is max(`cancellationCharge + restMinLockDemand` and `allocation cost`)

 this is cancellation charge
```
func (sa *StorageAllocation) cancellationCharge(cancellationFraction float64) (currency.Coin, error) {
	cost, err := sa.cost()
	if err != nil {
		return 0, err
	}
	return currency.MultFloat64(cost, cancellationFraction)
}
```

this is restMinLOck
```
func (sa *StorageAllocation) restMinLockDemand() (rest currency.Coin, err error) {
	for _, details := range sa.BlobberAllocs {
		if details.MinLockDemand > details.Spent {
			rest, err = currency.AddCoin(rest, details.MinLockDemand-details.Spent)
			if err != nil {
				return
			}
		}
	}
	return
}
```

can get the cancellationFraction from storage config from sharders
https://dev3.zus.network/sharder01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/storage-config
