### ISSUE TITLE
Unforbid allocation

### ISSUE THREAD

**Issue by iamibadd** [0chain/gosdk#1059]
@boddumanohar as per our discussion, we need to have `unforbid` allocation operations. 

Use case:

- Make an allocation `uploadonly` and forbid all other operations.
- Allow all operations for the same allocation.

**Comment by guruhubb** [comment]
We should have tests for different allocation types @Kishan-Dhakan @Jayashsatolia403 

1. `Frozen` allocations are` read-only`.
2. `Upload-only` allocations do not allow update, rename, delete, move, copy.  
3. All allocations should be able to extend duration, add/drop blobber regardless of frozen, upload-only status.

**Comment by Jayashsatolia403** [comment]
We are already covering 2nd. Let me create an issue to add cases for 1 and 3.

**Comment by guruhubb** [comment]
Its decided for now not to allow unforbid allocation. So its a one-way process
