### ISSUE TITLE
cannot download files smaller than 64K

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#1091]
currently blobbers in dev network as deployed with `d6bf90311851af517a9357372ae24fc26c70c7e6`

and gosdk version that should be used with this version of blobber is: `54c91490b14ea61bd37e1f3d9a908eb81cb818ef`

with this versions, when I try to download a file with less than 64K in size, I get error: `no data shards` error.

if the file size is greater than 64K, it works without any issues

**Comment by din-mukhammed** [comment]
Downloading files with size smaller than 64K seem to be working fine on `sprint-july-1`, 
e.g. screenshot: downloading file with size 13
![image](https://github.com/0chain/gosdk/assets/52813950/86117977-f39a-4b91-85c3-c66859b34645)

**Comment by boddumanohar** [comment]
thanks for checking. Will check this again on Monday (after new staging deployment) and close if the issue still exists.

**Comment by boddumanohar** [comment]
able to download closing it.
