### ISSUE TITLE
new wasm functions: `newAllocationTokensToLock` and `updateAllocationTokensToLock`

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#1098]
`newAllocationTokensToLock` --> given an new allocation request, the parameters should be exactly same as a `newallocation` and  should return the minimum no of tokens to lock in writepool 

https://github.com/0chain/0chain/blob/e0abd961d628fa65c87746f21b3f5467b0e0c62b/code/go/0chain.net/smartcontract/storagesc/models.go#L849-L862

`newAllocationTokensToLock` --> given an update allocation request, the parameters should be exactly same as `updateallocation` and should return the minimum no of tokens to lock in writepool

https://github.com/0chain/0chain/blob/e0abd961d628fa65c87746f21b3f5467b0e0c62b/code/go/0chain.net/smartcontract/storagesc/models.go#L849-L887

**Comment by boddumanohar** [comment]
when trying to reduce allocation, the allocation size cannot be less than used size.

https://github.com/0chain/0chain/blob/978a1b62d75438b5e40302844ae1b7be5d8ab1a2/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1136-L1139

**Comment by peterlimg** [comment]
[getAllocationMinLock](https://github.com/0chain/gosdk/blob/f147f88e8bbe65ec5f2c9823e541b06a9a468459/wasmsdk/allocation.go#L208) can be used for get min lock tokens for new allocation. I'll add the new endpoint for getting min lock requirements for updating allocation.
