### ISSUE TITLE
Transaction fee cache issue in wasm

### ISSUE THREAD

**Issue by peterlimg** [0chain/gosdk#1112]
Currently we store the estimated transaction fee in a global cache, and the cached value will be used as the fee next time when new transaction is about to be submitted. So if we run any txn 0 fee such as faucet pour SC first, the cached the fee will be `0`, therefore if we try to do another transaction such as create new allocation transaction, the fee of value `0` will be used and we will failed to send the transaction. zboxcli and zwallet may not have the issue as the cache is fresh in each run of the command, but seems wasm will have problem as the cache persist before the webpage is reloaded.  @dabasov @boddumanohar please help to. check if this is true.

**Comment by dabasov** [comment]
looks like this one was not fully fixed, https://github.com/0chain/gosdk/pull/1069/files
we need to cache all the table simply
