### ISSUE TITLE
Clean up unused methods

### ISSUE THREAD

**Issue by dabasov** [0chain/gosdk#1193]
Remove most of the methods except delete and chunked_upload as they are used for repair.

**Comment by boddumanohar** [comment]
there are still places where UI is using non-multi operation related functions: 

https://0chain.slack.com/archives/G01EXH6EYC9/p1694270828926659?thread_ts=1693184596.807889&cid=G01EXH6EYC9

So created seperate issue to track UI related changes: https://github.com/0chain/web-apps/issues/8591
