### ISSUE TITLE
Error when n+1 files are uploaded

### ISSUE THREAD

**Issue by dabasov** [0chain/gosdk#1194]
Error on client if it tries to upload file that were already uploaded on other blobbers successfully, consider using hashes to check file version or simply force error

Steps to reproduce:
- upload ~/file.png to / on blobber1-blobber6(4+2)
- due network issue, it fails on blobber6. it is consider as success because data+shard = 5. actually fragment of blobber6 is lost for user.
- user update ~/file.png with new content, and upload(not update) it again
- cli will skip upload to blobber1-blobber5 due to duplicated_file error, and still upload new framment6 to blobber6, and says success on this uploading

for now, we have old fragments(1-5) on blobber1-blobber5, and new fragment6 on blobber6. but they are belong to different file content.

**Comment by Hitenjain14** [comment]
Fixed by #1195
