### ISSUE TITLE
Pagination not working as expected for listObjects function

### ISSUE THREAD

**Issue by panchami-zus** [0chain/gosdk#1377]
Gosdk version: `v1.12.0-RC1`
Network: `Dev`

Only 49 files are being displayed no matter what `limit` and `offset` param is passed to the `listObjects` function.

Ref: https://0chain.slack.com/archives/G014PQ61WNT/p1705970443485759?thread_ts=1705970402.417639&cid=G014PQ61WNT

**Comment by Hitenjain14** [comment]
Resolved
