### ISSUE TITLE
[FEATURE] Revamp the build-pipelines for gosdk

### ISSUE THREAD

**Issue by kushthedude** [0chain/gosdk#186]
- Invoke golangci-lint in the build pipelines
- Invoke grpc-client setup as well as blobber server checkup in the pipeline.
- Invoke grpc-tests in the pipeline to be run for every PR

**Comment by cnlangzi** [comment]
@kushthedude  golangci-lint is done . grpc stuff should be added on integration-test, right? should we close this issue now?
