### ISSUE TITLE
porting wallet and zbox sdk to wasm

### ISSUE THREAD

**Issue by Rizary** [0chain/gosdk#219]
I have done porting `wallet.go` and zbox's `sdk.go`  to WebAssembly with #135 (completed) and #190 (ongoing). The purpose of this work is to make both zcncore's wallet and zbox's sdk available in WASM format so any other language that want to use it can just target the `.wasm` file and use it in their chosen programming language.

Right now, writing test is also still on going process.

**Comment by cnlangzi** [comment]
it is done on wasmsdk folder
