### ISSUE TITLE
Request: Increase limit of total blobbers per allocation above 32.

### ISSUE THREAD

**Issue by sculptex** [0chain/gosdk#23]
As per (https://github.com/0chain/gosdk/pull/22) there is currently a hard limit of 32 blobbers (data+parity) per allocation due to use of unit32 shifted bit mask. Since the EC technology itself has no such hard limit for this, I propose we increase this to at least 64 (uint64?) or even higher (uint256?!) because I can easily envisage use case for above 32 blobbers.

**Comment by stewartie4** [comment]
This fix is to prevent incorrect EC as the code base is today
However, I agree we should increase the mask to allow more blobbers.
I'd be interested to know why there is a mask at all and what Saswata's opinion is on increasing the mask as he was happy enough with a 32 limit when I ran the same option past him

**Comment by sculptex** [comment]
Re: practical limit for max blobbers, we should not encourage very high data ratios, it simply reduces efficiency, particularly for small files. However, there are potential use cases for high parity where increased redundancy and distribution are required. One issue this raises (when using high parity) is amount of shards that actually get downloaded. I think it currently (attempts to) download all shards but it should only attempt to download perhaps a bit more than the number of data shards to remain relatively efficient with high parity.

**Comment by stewartie4** [comment]
This should be closed. The limit is now 128 as per https://github.com/0chain/gosdk/pull/27/
