### ISSUE TITLE
DownloadFromAuthTicket does not set owner correctly when 3rd party pays

### ISSUE THREAD

**Issue by Sriep** [0chain/gosdk#246]
[downloadBlobberBlock](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/blockdownloadworker.go#L141) always sets the owner to be the client. This is wrong when a 3rd party pays and the owner is someone else.

The end result seems to be that 0chain `read_redeem` can fail as it gets confused verifying the signature, assuming the owner has signed it.

**Comment by Sriep** [comment]
Actually on investigation this is clearly confusing, the cause of the problem was in 0chain https://github.com/0chain/0chain/pull/519.

**Comment by lpoli** [comment]
I've included this in coming PR in refactored download.
