### ISSUE TITLE
After smart contract error get error cause from event databse

### ISSUE THREAD

**Issue by Sriep** [0chain/gosdk#326]
If a smart contract fails we should get the error from the Event database and return that to the user. We can put the code in places like [smartContractTxnValueFee](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/sdk.go#L1084)

This is needed as the cause of the error is not returned by the smart contract. 
As there might be a delay updating the Event database we should repeat this with a timeout. However, this should all be hidden from the user who will just get a friendly error message returned by goSDK.

This requires https://github.com/0chain/0chain/issues/771 to be completed.

**Comment by shaktals** [comment]
@Sriep I'd like to work on this, looking into it

**Comment by shaktals** [comment]
I'd need guidance to figure how to solve it.

**Comment by dabasov** [comment]
fixed with chargeable errors
