### ISSUE TITLE
[FEATURE] Provide fee for transactions

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/gosdk#384]
Gosdk makes transactions with 0 fees, it won't work on mainnet.
E.g: 
```
func smartContractTxnValue(sn transaction.SmartContractTxnData, value int64) (hash, out string, err error) {
	return smartContractTxnValueFee(sn, value, 0)
}
```

```
txn, err := zcncore.NewTransaction(statusBar, 0)
```

Proposal: to use user provided fees and if not provided use `min_fee` as default.

See: 
- https://github.com/0chain/zwalletcli/issues/85
- https://0chain.slack.com/archives/G01FYNN6DK4/p1645097379703449

**Comment by peterlimg** [comment]
@bisakhmondal is working on it on https://github.com/0chain/gosdk/pull/623, but not responding to the changes, I'll check and close those PRs.
