### ISSUE TITLE
bls + mcl - remove bls-go-binary from go.mod

### ISSUE THREAD

**Issue by bernardoaraujor** [0chain/gosdk#41]
# Request For Comment

I propose the removal of `bls-go-binary` listing inside `go.mod`.
To be replaced with `Makefile` logic that fetches and builds specific releases of `bls` + `mcl` from their upstream `github.com/herumi/*` repos.

# Why?

- In blockchain, code is law.
- Never depend on something you didn't compile yourself in your CI/CD pipeline. Even if you trust who compiled it, you are compromised as soon as they are.
- Avoid potential auditability issues.
- Prebuilt binaries shrink the spectrum of Embeddable possobilities.

**Comment by mallochine** [comment]
yeah that's not going to work because bls-go-binary is a go API to the C++ builds of bls+mcl

so gosdk must integrate bls-go-binary.

I have a branch where we replace bls+mcl with MIRACL, so this is a moot issue anyway.

We can close this issue out unless you have more questions

**Comment by bernardoaraujor** [comment]
ok `MIRACL` sounds like a good solution, thanks for pointing that out
closing.
