### ISSUE TITLE
pad chunk with zero byte if its data size is less than chunk size (64KB)

### ISSUE THREAD

**Issue by cnlangzi** [0chain/gosdk#426]
see detail https://0chain.slack.com/archives/GREHVKQKS/p1649229706644469?thread_ts=1647253193.950549&cid=GREHVKQKS

**Comment by lpoli** [comment]
To put it exactly, if you've `n` data-shards then your fragment size is `n * 64KB`.
So if fragment taken from file is lesser than `n * 64KB` we would pad with zero bytes and make upto `n * 64KB`.

**Comment by dabasov** [comment]
duplicate https://github.com/0chain/gosdk/issues/451
