### ISSUE TITLE
Revert to zero padding

### ISSUE THREAD

**Issue by lpoli** [0chain/gosdk#451]
Currently with chunked upload zero padding has been removed. As per discussion in slack channels, For a blobber, it should get minimum of `blockSize` amount of data which is `64KB` or multiple of `blockSize`.

Give there are `n` data-blobbers and blocksize is `64KB`, the reading should be done as follow:
```
chunkSize  := n * blockSize
chunkNums := int(math.Ceil(float64(fileSize) / float64(chunkSize)))

resultantSize := chunkNums * chunkSize
numPaddings := resultantSize - fileSize

reader := io.MultiReader(originalFileReader, bytes.NewReader(make([]byte, numPaddings)))

```

**Comment by guruhubb** [comment]
Is this same as https://github.com/0chain/gosdk/issues/426?

**Comment by cnlangzi** [comment]
@guruhubb  yes. it is same as https://github.com/0chain/gosdk/issues/426

**Comment by lpoli** [comment]
The requirement is to have minimum block size i.e. 64KB. 
We can apply this requirement with pricing i.e. minimum cost shall be cost of 64KB.
So it should be like this:
If writemarker has size `S` and write price is `W` then cost of writing S bytes = `Ceil_Of(S / 64KB) * W`

@dabasov Please let us know if you think otherwise

**Comment by dabasov** [comment]
related to https://github.com/0chain/0chain/issues/1816
