### ISSUE TITLE
Add multiple API providers to convert ZCN to USD

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/gosdk#463]
- We need to ensure we have multiple API providers to convert ZCN to USD so we don't hit rate limits on any one provider. Alternatively, we can buy a plan from any one vendor.
- See: https://0chain.slack.com/archives/C02AV6MKT36/p1652775265327279
- Whoever takes this issue also needs to turn `price_in_usd` config in `blobber-values.yaml` in `dev-*` networks to `true`.

**Comment by sculptex** [comment]
@Kishan-Dhakan there was previously talk of this (price source) being provided by an Oracle-type BlockChain, I don't know latest on this. Of course there should be redundancy built-in.

Regarding rate limits and recent downtime of CoinGecko, I created [sculptex-coingeckoapicache](https://github.com/sculptex/coingeckoapicache) to tolerate this, this might be also be considered although I am not sure what entity would be suitable host this for mainnet.

It is implemented at:-
https://coingecko.zcdn.uk/api/v3/coins/0chain?localization=false
