### ISSUE TITLE
Wallet downloaded from 0Chain main page cannot be used for zwallet cli

### ISSUE THREAD

**Issue by Dmdv** [0chain/gosdk#511]
When I download the wallet from wallet details page, i.e. https://dev-nonce.devnet-0chain.net/wallet/detail 
it comes in the following format.

Both are with `"version": "1.0"`,

```json
{
  "id": "5xxx",
  "version": "1.0",
  "creation_date": 1657630352,
  "public_key": "exxx",
  "secretKey": "8xxx",
  "mnemonic": "mnemonicxxx",
  "timeStamp": 1657630353547,
  "cluster_name": "local",
  "balance": {
    "txn": "axxx",
    "round": 72301,
    "balance": 5000000000,
    "nonce": 5
  }
}

```

However GOSDK expects the wallet in the following format

```json
{
  "client_id": "dxxx",
  "client_key": "9xxx",
  "keys": [
    {
      "public_key": "9xxx",
      "private_key": "fxxx"
    }
  ],
  "mnemonics": "mnemonicsxxx",
  "version": "1.0",
  "date_created": "2022-07-12T23:47:31+05:00",
  "nonce": 0
}

```

Is it by design or downloadable wallet must be in compliance with GOSDK format?

**Comment by cnlangzi** [comment]
@Dmdv  hmm, it works with cli.

**Comment by sculptex** [comment]
Irrespective, the mnemonic should be used to restore the wallet to its native target format and actually on CLI many tasks can be performed just with public and private key pair.
