### ISSUE TITLE
NFT methods needed to be exposed in wasm

### ISSUE THREAD

**Issue by gerta17** [0chain/gosdk#525]
This is the list of Chalk APIs that we need for integration:

1. Deploy Contract API for Public Mint
2. Deploy Contract API for Pack Mint
3. Deploy Contract API for Owner Mint
4. My NFT
5. View NFT
6. Mint NFT
7. Latest Creations
8. Explore NFTs

**Comment by cnlangzi** [comment]
it is done by js
