### ISSUE TITLE
Concurrent operations on allocations are flaky

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/gosdk#695]
![image](https://user-images.githubusercontent.com/42718091/208937593-d1051a5e-5fe3-4aa4-85d9-b4c060cd4672.png)

Test; TestFileRename/Rename_and_delete_file_concurrently,_should_work

Note: This is not limited to rename and delete, it happens in other concurrent CRUD operations

**Comment by lpoli** [comment]
For the record I think this issue is due to lock expiration. 
Commit operation should acquire lock before sending commit request to the blobber. If this acquired lock is unlocked for 30 seconds then other commit operation can take over the lock.

The solution would be to refresh the lock.
