### ISSUE TITLE
gosdk(videostreaming): add transcode feature on upload

### ISSUE THREAD

**Issue by cnlangzi** [0chain/gosdk#712]
`play media file chunk by chunk` feature only works on `fMp4` or `webp`. a transcode feature should be added on file upload. all non-fragmented mp4 file should be converted to fragmented mp4 and upload.
see detail https://0chain.slack.com/archives/G014PQ61WNT/p1680750942551589?thread_ts=1680721705.377029&cid=G014PQ61WNT

it will let feature called `video streaming` supported on web. on mobile/desktop, it should be simply implemented with https://github.com/0chain/zboxcli#streaming 

## TODO
- add a feature option `--web-streaming` to enable `play it on web with streaming feature`. 
- if `--web-streaming` is turn on, a raw video file should be transcoded into another .mp4 file with fMP4 encoding
- both the raw video file and fMP4 file should be uploaded
- when it is played on web player, we should check if there is related mp4 file with fmp4 encoding, if yes, play it with streaming feature, if not, only play it after fully download.
- this feature should be implemented on cli/mobile/desktop/web apps.

**Comment by guruhubb** [comment]
re `both the raw video file and fMP4 file should be uploaded` we don't need to upload both files but just the fmp4 only.
