### ISSUE TITLE
[flake] stake pool lock fails with `miner not found or genesis miner used`

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/gosdk#860]
Stake pool fails with ` miner not found or genesis miner used` error even though miner is in the network

**Comment by peterlimg** [comment]
Perhaps the same issue as #2240

**Comment by peterlimg** [comment]
@Kishan-Dhakan do we still have the errors with latest staging 0chain?

**Comment by Kishan-Dhakan** [comment]
Not seeing it, will re-open the issue if it appears again
