### ISSUE TITLE
EOF when downloading file from blobber

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/gosdk#889]
File download is returning with EOF error.

**EOF** is basically responded when client uses a http connection that is closed by the server.
Its not easy to replicate this error and fix it but having connection ttl should have been fine.

Network details : 

2 Blobbers and 2 Validators 

Blobber1 : 0 read_price | 0.1 write_price
Blobber2 : 0.01 read_price | 0.1 write_price

Allocation Details : 

1 data 1 parity
1 GB size 

File Size : 0.1GB 

Both blobbers and validators are staked 1 tokens each.

**Comment by din-mukhammed** [comment]
https://0chain.slack.com/archives/C03788G8N2D/p1680955796513729
