### ISSUE TITLE
blobbers not making progress when given MIRACL public keys

### ISSUE THREAD

**Issue by mallochine** [0chain/gosdk#92]
the blobber "cluster" and anything else using gosdk cannot handle MIRACL public keys right now. That is why I am seeing issue of blobbers not being able to commit a file.

This commit adds a function to translate MIRACL public keys into herumi/bls keys.

It is backward compatible with the herumi/bls keys. If it gets herumi pub key, it will just return it.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |
