### ISSUE TITLE
wasm sdk: recover from panic

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#941]
when ever there is an panic within wasm functions, for example: 

https://github.com/0chain/gosdk/blob/fc71195dd1e876de6d9d375005aea8a98e8972ae/wasmsdk/allocation.go#L52-L53

In this wasm function, `datashards` is expected to be int. But if you pass `dataShards` as string, then gowasm crashes and returns an error 

```
Go instance is not active
```

To fix this, the go wasm instance should be able to recover from panic during its execution.

**Comment by cnlangzi** [comment]
please convert it into number before call it.

**Comment by boddumanohar** [comment]
The fix doesn't seems solve the isse completely. whenever there is a panic in wasm, the web-apps breatks.

**Comment by cnlangzi** [comment]
it fixed input panicking issue. but don't catch generic panicking issue in code.

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/gosdk/pull/1071
