### ISSUE TITLE
Download command is not working in cli

### ISSUE THREAD

**Issue by kcratss** [0chain/gosdk#967]
Just upload the any image or video file and try to download it. here's the command and response screenshot

![image](https://github.com/0chain/gosdk/assets/17355542/9910d64d-999d-4f46-b978-35fa5511e8ae)

**Comment by din-mukhammed** [comment]
![image](https://github.com/0chain/gosdk/assets/52813950/0cff0b5e-fc01-4690-bfa8-5644f8f7b5c3)

@dabasov The download command is working fine after last download optimizations PRs were merged.

[reported](https://0chain.slack.com/archives/G014PQ61WNT/p1685007495753619?thread_ts=1684998151.192959&cid=G014PQ61WNT) "Timestamp is for future in the readmarker" error is expected if timestamp is not correct. I manually modified system time to 1 minute in the future and got the same result:
![image](https://github.com/0chain/gosdk/assets/52813950/0eb41600-c54b-4705-a526-0dc2bfefcf32)
