### ISSUE TITLE
flakiness in gosdk unit tests

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#981]
```
Diff: 0: FAIL:  (*http.Request=&{DELETE http://Test_All_Blobber_Error_On_Delete_Attribute_Failuremockblobberurl2/v1/file/upload/mock%20transaction%20id?connection_id=1234567890&path=mock%2Fremote%2Ffile%2Fpath HTTP/1.1 1 1 map[X-App-Client-Id:[mock client id] X-App-Client-Key:[mock client key] X-App-Client-Signature:[]] <nil> <nil> 0 [] false Test_All_Blobber_Error_On_Delete_Attribute_Failuremockblobberurl2 map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc000f88c60}) not matched by func(*http.Request) bool
```
there is a flakiness in Unit tests: https://github.com/0chain/gosdk/actions/runs/5047180230/attempts/1 (failed), https://github.com/0chain/gosdk/actions/runs/5047180230/jobs/9053893426 (passed) without any changes.

This is happening only in CI

**Comment by boddumanohar** [comment]
@cnlangzi say: 

>if it works on local, but fails on github ci. it means there are some mocks that is not cleanup properly. so it fails on sever due to concurrent issue. please check your teardown code(or it is missed fully).  migrate to docker should not help to fix it.

**Comment by peterlimg** [comment]
The mock files are committed, and we run the tests from a fresh golang:1.18 container each time in the CI. So perhaps the concurrency caused the issue.
